/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface InstantiateMsg {
  archid_registry_addr: Addr;
  count: number;
  cw721_archid_addr: Addr;
  denom: string;
}
export type ExecuteMsg = {
  increment: {};
} | {
  mint_domain: {
    domain_name: string;
  };
} | {
  renew_domain: {
    domain_name: string;
  };
} | {
  schedule_auto_renew: {
    domain_name: string;
  };
} | {
  cancel_auto_renew: {
    domain_name: string;
  };
} | {
  set_default: {
    domain_name: string;
  };
} | {
  start_cron_job: {};
} | {
  stop_cron_job: {};
} | {
  deposit: {};
} | {
  withdraw: {};
};
export type QueryMsg = {
  get_count: {};
} | {
  query_errors: {};
} | {
  query_domain_default: {
    address: Addr;
  };
} | {
  query_renew_map: {
    domain_name: string;
  };
} | {
  query_renew_jobs_map: {
    block_id: number;
  };
};
export interface GetCountResponse {
  state: State;
}
export interface State {
  callback_height: number;
  count: number;
  owner: Addr;
  renew_status: number;
  status: number;
  [k: string]: unknown;
}
export interface DomainDefaultResponse {
  domain_id: string;
}
export interface QueryErrorsResponse {
  errors: SudoError[];
}
export interface SudoError {
  contract_address: string;
  error_code: number;
  error_message: string;
  input_payload: string;
  module_name: string;
}
export interface RenewJobsMapResponse {
  renew_jobs: string[];
}
export type Binary = string;
export interface RenewMapResponse {
  renew_info?: RenewInfo | null;
}
export interface RenewInfo {
  block_idx: number;
  callback_height: number;
  domain_id: string;
  err_message?: string | null;
  execute_msg: Binary;
  owner: Addr;
  status: number;
  [k: string]: unknown;
}