/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export type Uint128 = string;
export interface InstantiateMsg {
  admin: Addr;
  base_cost: Uint128;
  base_expiration: number;
  cw721: Addr;
  wallet: Addr;
}
export type ExecuteMsg = {
  register: {
    name: string;
  };
} | {
  withdraw: {
    amount: Uint128;
  };
} | {
  renew_registration: {
    name: string;
  };
} | {
  extend_subdomain_expiry: {
    domain: string;
    expiration: number;
    subdomain: string;
  };
} | {
  update_resolver: {
    name: string;
    new_resolver: Addr;
  };
} | {
  register_subdomain: {
    domain: string;
    expiration: number;
    new_owner: Addr;
    new_resolver: Addr;
    subdomain: string;
  };
} | {
  remove_subdomain: {
    domain: string;
    subdomain: string;
  };
} | {
  update_config: {
    config: Config;
  };
} | {
  update_user_domain_data: {
    metadata_update: MetaDataUpdateMsg;
    name: string;
  };
};
export interface Config {
  admin: Addr;
  base_cost: Uint128;
  base_expiration: number;
  cw721: Addr;
  wallet: Addr;
}
export interface MetaDataUpdateMsg {
  accounts?: Account[] | null;
  description?: string | null;
  image?: string | null;
  websites?: Website[] | null;
}
export interface Account {
  account_type?: string | null;
  profile?: string | null;
  username?: string | null;
  verfication_hash?: string | null;
  [k: string]: unknown;
}
export interface Website {
  domain?: string | null;
  url?: string | null;
  verfication_hash?: string | null;
  [k: string]: unknown;
}
export type QueryMsg = {
  resolve_record: {
    name: string;
  };
} | {
  record_expiration: {
    name: string;
  };
} | {
  resolve_address: {
    address: Addr;
  };
} | {
  config: {};
};
export interface RecordExpirationResponse {
  created: number;
  expiration: number;
}
export interface ResolveAddressResponse {
  names?: string[] | null;
}
export interface ResolveRecordResponse {
  address?: string | null;
  expiration: number;
}